branch-defaults:
  default:
    environment: my-env
    group_suffix: null
environment-defaults:
  cliprivatebin:
    branch: null
    repository: null
global:
  application_name: cli_private_bin
  branch: null
  default_ec2_keyname: Private_bean_key
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
